### PR TITLE
Support Python>=3.9

### PR DESCRIPTION
**Pull request by bjhardcastle**
- adds backport for StrEnum

### CODE REVIEW

**Comment by bjhardcastle** [comment]
@zvikagart shall I adjust this line to test the examples on the lower python version too?
https://github.com/codeocean/codeocean-sdk-python/blob/8965c27a54ec614ddf31cc5b42b08cc0bd8996c9/.circleci/config.yml#L6

**Comment by zvikagart** [comment]
Testing against multiple python versions would require a test matrix in Hatch: https://hatch.pypa.io/latest/meta/faq/#hatch_1

**Comment by bjhardcastle** [comment]
@zvikagart sorry, it wasn't clear to me how to get this working with Hatch, but got it to work on circleci for multiple versions (note this now includes running `python -m unittest`)

**Comment by bjhardcastle** [comment]
@zvikagart Any chance we could get this released soon?

**Comment by zvikagart** [comment]
Hey @bjhardcastle, yes, work on this is scheduled to complete in July.

**Comment by zvikagart** [comment]
@bjhardcastle I've merged your work plus some changes and published [v0.1.4](https://pypi.org/project/codeocean/0.1.4/).
Thanks for the contribution!

**Pull request closed without merging**
